// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYk8Q4_WxKs084Rhr4rJK-mQWDVsIjDjI',
    appId: '1:272014607192:web:69b52e3a899aee7af69b2d',
    messagingSenderId: '272014607192',
    projectId: 'agenda-contatos-curso-12af9',
    authDomain: 'agenda-contatos-curso-12af9.firebaseapp.com',
    storageBucket: 'agenda-contatos-curso-12af9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1qX5fgaSoXyjOuDE-lu4469o4M3tfGt4',
    appId: '1:272014607192:android:2b0c269d30ababdcf69b2d',
    messagingSenderId: '272014607192',
    projectId: 'agenda-contatos-curso-12af9',
    storageBucket: 'agenda-contatos-curso-12af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7q_tqkisq7dzaMj2uvh0SxwxkeuhSeg',
    appId: '1:272014607192:ios:9c22fdaf81c512f8f69b2d',
    messagingSenderId: '272014607192',
    projectId: 'agenda-contatos-curso-12af9',
    storageBucket: 'agenda-contatos-curso-12af9.firebasestorage.app',
    iosBundleId: 'com.example.agendaContatosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7q_tqkisq7dzaMj2uvh0SxwxkeuhSeg',
    appId: '1:272014607192:ios:9c22fdaf81c512f8f69b2d',
    messagingSenderId: '272014607192',
    projectId: 'agenda-contatos-curso-12af9',
    storageBucket: 'agenda-contatos-curso-12af9.firebasestorage.app',
    iosBundleId: 'com.example.agendaContatosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYk8Q4_WxKs084Rhr4rJK-mQWDVsIjDjI',
    appId: '1:272014607192:web:32d6b0f9c8bc398cf69b2d',
    messagingSenderId: '272014607192',
    projectId: 'agenda-contatos-curso-12af9',
    authDomain: 'agenda-contatos-curso-12af9.firebaseapp.com',
    storageBucket: 'agenda-contatos-curso-12af9.firebasestorage.app',
  );
}